
spring:
  data:
    mongodb:
      uri: mongodb+srv://reshmika:Assignment1234@cluster0.stznbbv.mongodb.net/assets?retryWrites=true&w=majority
  application:
    name: USER-SERVICE
server:
  port: 8080


